name: Run unit tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        sudo apt install -y python3 python3-pip
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        for day in day*; do
          echo "::group::$day"

          flags=$(.github/workflows/day-flags.sh "$day")
          if [ -n "$flags" ]; then
            echo "::warning::Running $day with extra flags $flags"
          fi

          ./run.sh "$day" $flags
          echo "::endgroup::"
        done
